version: "3.1"
networks: 
  NOPENINT:

services:
  nodejs:
    image: "node:alpine"
#    image: "ageapps/docker-node-mongo"
#    user: "node"
    working_dir: /code/shopify-dashboard
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/code
    ports:
          - "3000:3000"
          - "8000:8000"
          - "80:80"
    expose:
      - "3000"
#    command: "npm run start"
    tty:  true
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - NOPENINT



  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: n0p3n1nt
    volumes:
      - mongoDataBase:/data/db 
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - NOPENINT


volumes:
  mongoDataBase:
    driver: local
