version: "3.1"
services:
  nodejs:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
          - "3000:3000"
          - "8000:8000"
    expose:
      - "3000"
#    command: "npm run start"
    tty:  true

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: D0z1n2ss
    volumes:
      - mongoDataBase:/data/db 
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    expose:
      - "27017"
    ports:
    - "27017:27017"


volumes:
  mongoDataBase:
    driver: local